---
 
- name: Notify instance error
  hosts: localhost

  tasks:
  - name: print Instance Failure
    debug: 
       msg: "Provisioning instance failure! Review related logs"
      
  - name: Sent telegram notification
    telegram:
       token: "{{ token }}"
       chat_id: "{{ chatid }}"
       msg: Provisioning instance failure! Review related logs
